### ISSUE TITLE
gromacs

### ISSUE THREAD

**Issue by ytzhang-hub** [Jerkwin/Jerkwin.github.io#60]
有人用过membuilder去建过分子生物膜吗，以便生成gromacs的输入文件，我试了好久，一直是The requested URL was not found on this server.这是为什么啊？

**Comment by Jerkwin** [comment]
不要在这里问这种问题, 到群里去问.

**Comment by ytzhang-hub** [comment]
你好，哪里有专门的群啊，没找到所以来GitHub找找。

发件人：Jerkwin ***@***.***>
发送日期：2021-06-26 12:15:09
收件人："Jerkwin/Jerkwin.github.io" ***@***.***>
抄送人：ytzhang-hub ***@***.***>,Author ***@***.***>
主题：Re: [Jerkwin/Jerkwin.github.io] gromacs (#60)

不要在这里问这种问题, 到群里去问.

**Comment by Jerkwin** [comment]
网站首页最下面有群信息.
