### ISSUE TITLE
科技绘图的调色板是否可以添加HEX列

### ISSUE THREAD

**Issue by TigerZhao007** [Jerkwin/Jerkwin.github.io#61]
2018-08-20-科技绘图的调色板.md
正如作者在博客中写到的那样，最方便的方式就是直接定义为相应的变量，不仅仅是在gnuplot中，在其他如R，python中也可以。
感谢作者做出了一个可视化的页面，但是这个页面中并没有提供赋值某个调色板的HEX的所有变量的复制方式，还需要打开源码查找复制，较为麻烦。
是否能在最后调色板的展示部分，添加一列，就是这个调色板的HEX的数值。

**Comment by Jerkwin** [comment]
意见很好, 已经加了一个复制功能, 但限于精力, 只在Chrome上测试通过.
